# Generated by Django 5.1.5 on 2025-01-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privatemessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
