# Generated by Django 5.1.5 on 2025-02-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_privatemessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
