# Generated by Django 5.1.5 on 2025-02-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_privatemessage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='is_deleted',
            new_name='deleted',
        ),
    ]
