# Generated by Django 5.1.5 on 2025-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_is_deleted_privatemessage_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
