# Generated by Django 5.1.5 on 2025-05-14 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_callhistory_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='call_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('failed', 'Failed')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['caller', 'receiver'], name='chat_callhi_caller__874af5_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['start_time'], name='chat_callhi_start_t_efe1dd_idx'),
        ),
    ]
