# Generated by Django 5.1.5 on 2025-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_callhistory_call_type_alter_callhistory_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='callhistory',
            name='chat_callhi_caller__874af5_idx',
        ),
        migrations.RemoveIndex(
            model_name='callhistory',
            name='chat_callhi_start_t_efe1dd_idx',
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='call_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call')], max_length=10),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='status',
            field=models.CharField(choices=[('missed', 'Missed'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=10),
        ),
    ]
