# Generated by Django 5.1.5 on 2025-05-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_callhistory_chat_callhi_caller__874af5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='status',
            field=models.CharField(choices=[('missed', 'Missed'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('timeout', 'Timeout'), ('offline', 'User Offline')], max_length=10),
        ),
    ]
