# Generated by Django 5.1.5 on 2025-05-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_callhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
