# Generated by Django 5.1.5 on 2025-05-19 10:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_userstatus_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='direction',
            field=models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming')], default=datetime.datetime(2025, 5, 19, 10, 56, 41, 897307, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='callhistory',
            unique_together={('caller', 'receiver', 'start_time')},
        ),
    ]
