# Generated by Django 5.1.5 on 2025-05-19 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_callhistory_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='callhistory',
            constraint=models.UniqueConstraint(fields=('caller', 'receiver', 'start_time'), name='unique_call'),
        ),
    ]
