# Generated by Django 5.1.5 on 2025-05-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_callhistory_unique_call'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='callhistory',
            name='unique_call',
        ),
        migrations.AlterUniqueTogether(
            name='callhistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='callhistory',
            name='direction',
        ),
    ]
